"""第 8 章：在这里写旋转位置编码的三个函数。"""

# def rotate_half(x): ...
# def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1): ...
# def precompute_freqs_cis(dim, end=32768, rope_base=1e6, rope_scaling=None): ...
